[package]
name = "vgm-audio-processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"
egui = "0.20.1"
eframe = "0.20.1"
rfd = "0.10.0"
midly = "0.5.3"
